### PR TITLE
Amazfit Neo initial support

### PR DESCRIPTION
**Pull request by kirbylife**
[Amazfit Neo](https://www.gsmarena.com/amazfit_neo_review-news-45962.php) initial support

What works:
- Sync steps correctly
- Shows the battery graph
- Allows to modify display items (HR, Steps, Weather, Stopwatch, Alarms and PAI only)
- Turn on the LED when lifting the wrist
- Synchronizes correctly the weather
- Find my phone
- Receive incoming calls
- Set alarms

What does not works:
- Cannot start activities (The watch support walk, running and bike)
- Receive notifications
- Cannot add the display item for burned calories, world clock, battery, and distance
- Cannot update the FW (It's a device abandoned by amazfit, I don't think it matters much)

Screenshot of the Amazfish app showing data extracted from an Amazfit Neo

Photo of an Amazfit Neo showing the weather

### CODE REVIEW

**Comment by jmlich** [comment]
I will try to provide some feedback. I have Amazfit Neo at home so I can also try it.

**Comment by piggz** [comment]
Great!

**Comment by kirbylife** [comment]
>I will try to provide some feedback. I have Amazfit Neo at home so I can also try it.

Great, I would really appreciate the feedback!!.

**Comment by jmlich** [comment]
I was able to reproduce your findings also with Ubuntu Touch. Pairing is somehow cursed (as expected). Find my phone is not implemented for Ubuntu Touch. Alarms doesn't work because some issue with time dialog.
I will try to prepare fix for that in separate pull request.

**Comment by piggz** [comment]
@jmlich so you are happy with the functionality of this to merge?

**Comment by jmlich** [comment]
I haven't check code, but how it works. It looks fine. Some review of code may disclose some issues still. Some missing features are working in GadgetBridge, but this can be improved in future.

**Pull request merged**
