### PR TITLE
Infinitime Simple Weather Service

### LINKED ISSUE #308: Weather Service rework
We would like to rework weather service to be simpler. It should work according following description:

> simple BLE API : it currently just take a 6 bytes buffer:
>  [0] = PacketType (only the value "0" is implemented, but this will allow for extensions in the future)
>  [1][2] = Temperature (16bits)
>  [3] = Precipitation type
>  [4] = Precipitation amount
>  [5] = Cloud amount
> 
> and... that's it! Amazfish just has to send the current values whenever they are updated.

### PR DESCRIPTION
**Pull request by jmlich**
This is was created in cooperation with @JF002 in scope of https://github.com/piggz/harbour-amazfish/issues/308. (Closes #308)
Documentation of the service and reasons are described in InfiniTime pull request.
https://github.com/InfiniTimeOrg/InfiniTime/pull/1924

I have update the osm weather in order to provide icon and temperature in qreal, because it converted from kelvins which adds unwanted error to the value (for example 274.9 kelvins ~ 274 - 273 = 1 deg, but it should be 274.9 - 273.15 = 1.75 ~ 2 deg). The weather icon is displayed in cityselection dialog.

### CODE REVIEW

**Comment by JF002** [comment]
We merged the new Simple Weather Service in InfiniTime. I did most of my tests using this PR in Amazfish, so I guess it's pretty safe to merge it ;-)
Thanks again a lot to @jmlich for their help on this topic!

**Comment by jmlich** [comment]
There is a few things to consider
- I have modified the openweather api to get temperature in float, not int. The floating point is better to keep precision while converting to Fahrenheit scale. I was looking into code and it should work for other devices, but I will be happier if you can check if it really works.
- Both weather services are still there. New InfiniTime just doesn't advertise the other GATT service, so it is created just right instance of Weather Class. For Old InfiniTime is it other way around. 
- I did some changes in weather selection page UI. It shows the icon now. Does it look fine on SailfishOS?

**Comment by jmlich** [comment]
I should probably rename the service to pinetimesimpleweatherservice to highlight that this is pinetime specific.

**Comment by piggz** [comment]
Good idea

**Pull request merged**
