### PR TITLE
Improved sleep analysis

### PR DESCRIPTION
**Pull request by vigejolla**

### CODE REVIEW

**Comment by vigejolla** [comment]
At least with firmware 1.1.5.16 the original code resulted in absolutely insane results, claiming that I slept most of the day. With these changes the values are at least quite near sane.

**Comment by piggz** [comment]
Could you re-base this and i'll give it a serious look.

**Comment by vigejolla** [comment]
> Could you re-base this and i'll give it a serious look.

I could, but I doubt it makes sense to merge it even after that. But giving that serious look is probably a good idea. What I mean is that it doesn't work like I would like to work even after my changes, even though it is a lot better. So after that serious look you might have the idea about what should really be done... In any case, I'll rebase it, maybe in the evening today.

**Comment by piggz** [comment]
I have merged some improved sleep analysis

**Comment by vigejolla** [comment]
> I have merged some improved sleep analysis

That sounds awesome, I guess I'll have to test it asap :)

**Pull request closed without merging**
