### PR TITLE
Fix Warnings regarding Connections in qml

### PR DESCRIPTION
**Pull request by marcoSchr**
This will fix all warnings regarding the "implicitly defined properties in Connections are deprecated" warnings

### CODE REVIEW

**Comment by piggz** [comment]
Thanks for this, will test it later ... out of interest, what are you running amazfish on?

**Comment by marcoSchr** [comment]
I am running on postmarketOS/Alpine Linux

**Comment by piggz** [comment]
Bit of a problem, this syntax seems to have appeared in qt 5.14 ... but I need to support qt 5.6 on sailfish!

**Comment by marcoSchr** [comment]
OK. Then I will need to check if there is a way to disable the warnings.

**Comment by piggz** [comment]
There is, like this
https://github.com/rinigus/pure-maps/blob/master/src/main.cpp#L132

**Comment by marcoSchr** [comment]
I saw you added this in bc9b9e377ae3908e91913bacbaa752f03f66ebd1.
I just tested it on postmarketOS, and I no longer get the warnings, thus I will close this pull request.

**Pull request closed without merging**
