### PR TITLE
Update harbour-amazfish-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
new strings translated

### CODE REVIEW

**Comment by piggz** [comment]
Please resolve conflicts, which were my doing.

**Comment by eson57** [comment]
Done..

**Comment by piggz** [comment]
Sorry, another conflict ... could you fix, and update to the latest release, and i'll do a translation only update

**Comment by eson57** [comment]
Done!

**Comment by eson57** [comment]
Sorry, had to correct one more time.

**Pull request merged**
